# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The little coder that could
author: Amir Barylko
email: amir@barylko.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my blog, thoughts, and musings

# Build settings
#theme: minima
theme: beautiful-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-spaceship
  - jekyll-sitemap

kramdown:
  input: GFM

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - .#*

avatar: "/assets/img/avatar.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

page-col: "#F3F3F3"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

site-css:
  - "/assets/css/style.css"

site-js:
  - "https://cdn.jsdelivr.net/npm/anchor-js/anchor.min.js"
  - "/assets/js/anchors.js"

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

social-network-links:
  email: "amir@barylko.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: amirci
  facebook: amirbarylko
  twitter: abarylko
  linkedin: amirbarylko

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# To use giscus comments:
# (0) Uncomment the following giscus section, (1) Enable Discussions in your GitHub repository,
# (2) Install the giscus app in your repository (details at https://giscus.app),
# (3) Fill in *all* the parameters below
# See more details about giscus and each of the following parameters at https://giscus.app
giscus:
  hostname: giscus.app # Replace with your giscus instance's hostname if self-hosting
  repository: amirci/blog-discussions
  repository-id: R_kgDONPdjKg # ID of your repository, retrieve this info from https://giscus.app
  category: Announcements # Category name of your GitHub Discussion posts
  category-id: DIC_kwDONPdjKs4CkRnH # ID of your category, retrieve this info from https://giscus.app
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: preferred_color_scheme
  loading: lazy

# Exclude from processing.

# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
